server:
  address: 0.0.0.0
  port: ${PORT}
  error.include-message: always
  ssl.trusted-certificates: /etc/ssl/cert.pem

spring:
  jackson.default-property-inclusion: non_null
  mvc.pathmatch.matching-strategy: ant_path_matcher
  data.mongodb.uri: ${MONGODB_URI:mongodb://localhost:27017/electricity-prices}

# MongoDB

# API
esios.url: https://api.esios.ree.es/archives/70/download_json

# Logging
logging:
  level:
    org.springframework.web: WARN
    ie.daithi: ${LOGGING_LEVEL:INFO}
    # org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/application.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui