server:
  address: 0.0.0.0
  port: ${PORT}
  error.include-message: always
  ssl.trusted-certificates: /etc/ssl/cert.pem

spring:
  profiles:
    active:
      ${SPRING_PROFILES_ACTIVE:prod}
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  mvc.pathmatch.matching-strategy: ant_path_matcher
  data.mongodb.uri: ${MONGODB_URI:mongodb://localhost:27017/electricity-prices}

# MongoDB

# API
ree.url: https://apidatos.ree.es/en/datos/mercados/precios-mercados-tiempo-real
esios.url: https://api.esios.ree.es/archives/70/download_json

# Logging
logging:
  level:
    ROOT: INFO
    ie.daithi: ${APP_LOG_LEVEL:INFO}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /