name: Publish to Dockerhub

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Build and Publish docker image to dockerhub
    permissions:
      contents: write
      pull-requests: write
      packages: read
    runs-on: self-hosted

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7,linux/arm64/v8 -t daithihearn/electricity-prices:latest -t daithihearn/electricity-prices:${{ github.ref_name }} --push .
